language: java
sudo: false

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start || echo Without Xvfb
  - wget https://github.com/oracle/graal/releases/download/vm-1.0.0-rc1/graalvm-ce-1.0.0-rc1-linux-amd64.tar.gz
  - tar fxvz graalvm-ce-1.0.0-rc1-linux-amd64.tar.gz
  - ./graalvm-1.0.0-rc1/bin/gu install -c org.graalvm.ruby
  - ./graalvm-1.0.0-rc1/bin/gu install -c org.graalvm.R
  - ./graalvm-1.0.0-rc1/bin/gu install -c org.graalvm.python
script:
  - ./.test.sh ./graalvm-1.0.0-rc1/ 2>&1 | grep -v ^Computed.*Last.*one
os:
- linux